# Generated by Django 2.2.3 on 2019-08-29 15:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Apartment',
                'verbose_name_plural': 'Apartments',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=3)),
                ('room_type', models.CharField(choices=[('A', 'Type A'), ('B', 'Type B'), ('C', 'Type C')], default=('B', 'Type B'), max_length=1)),
                ('room_available_status', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.Apartment')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ('room_no',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.CharField(help_text='Mô tả trong 100 ký tự', max_length=100)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ElectricNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('electric_number', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)])),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electric_numbers', to='core.Room')),
            ],
            options={
                'verbose_name': 'ElectricNumber',
                'verbose_name_plural': 'ElectricNumbers',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Room')),
                ('contract_type', models.CharField(choices=[('HĐ1T', '1 Month'), ('HĐ3T', '3 Months'), ('HĐ6T', '6 Months'), ('HĐ1N', '1 Year')], default=('HĐ3T', '3 Months'), max_length=4)),
                ('contract_no', models.CharField(max_length=10)),
                ('contract_started_at', models.DateTimeField(auto_now_add=True)),
                ('contract_end_at', models.DateTimeField(null=True)),
                ('services', models.ManyToManyField(related_name='contracts', to='core.Service')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
            bases=('core.room',),
        ),
    ]
